In [1]:
import torch

In [11]:
f = torch.nn.Sequential(torch.nn.Linear(2, 1), torch.nn.Sigmoid())

In [10]:
f(torch.randn(2))

tensor([2.1393], grad_fn=<AddBackward0>)

In [13]:
x = torch.randn(1,2, requires_grad=True)

In [47]:
y = f(x)

In [48]:
grad_x_f = torch.autograd.grad(y, x)[0]

In [49]:
grad_x_f

tensor([[0.0776, 0.1151]])

In [29]:
def log_bernoulli(z, y):
    return z*torch.log(y) + (1-z)*torch.log(1-y)

In [34]:
y.requires_grad_(True)
grad_y_logpy = torch.autograd.grad(log_bernoulli(1,y), y)[0]

In [50]:
grad_y_logpy@grad_x_f

tensor([[0.0978, 0.1451]])

In [30]:
grad_x_logpfx = torch.autograd.grad(log_bernoulli(1,y), x)[0]

In [46]:
grad_x_logpfx

tensor([[0.0978, 0.1451]])